document.writeln("    <footer class=\'footer\'>");
document.writeln("        <div class=\'wrapper footWrap\'>");
document.writeln("            <h2 class=\'footLogo\'>");
document.writeln("                <img src=\'./img/home/logo.png\' width=\'168\' height=\'54\'>");
document.writeln("            </h2>");
document.writeln("            <div class=\'browse\'>");
document.writeln("                <h3>Browse</h3>");
document.writeln("                <ul class=\'browseList\'>");
document.writeln("                    <li class=\'browseItem\'><a href=\'#\'>Invest</a></li>");
document.writeln("                    <li class=\'browseItem\'><a href=\'#\'>Home</a></li>");
document.writeln("                    <li class=\'browseItem\'><a href=\'product.html\'>Products</a></li>");
document.writeln("                    <li class=\'browseItem\'><a href=\'platforms_tow.html\'>Platforms</a></li>");
document.writeln("                    <li class=\'browseItem\'><a href=\'resources.html\'>Resources</a></li>");
document.writeln("                    <li class=\'browseItem\'><a href=\'about.html\'>About us</a></li>");
document.writeln("                    <li class=\'browseItem\'><a href=\'zaxis.html\'>Z-axis</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'concat\'>");
document.writeln("                <h3>Concat</h3>");
document.writeln("                <p>");
document.writeln("                    Coherix Headquarters 3980 Ranchero Dr. Ann Arbor, MI 48108");
document.writeln("                </p>");
document.writeln("                <div>");
document.writeln("                    <a href=\'tel:734-922-4073\'>Tel: 734-922-4073</a>");
document.writeln("                    <a href=\'fax:734-761-9193\'>Fax: 734-761-9193</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'about\'>");
document.writeln("                <h3>About</h3>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <img src=\'./img/home/social1.png\' width=\'26\' height=\'26\' />");
document.writeln("                </a>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <img src=\'./img/home/social2.png\' width=\'26\' height=\'26\' />");
document.writeln("                </a>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <img src=\'./img/home/social3.png\' width=\'26\' height=\'26\' />");
document.writeln("                </a>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <img src=\'./img/home/social4.png\' width=\'26\' height=\'26\' />");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'copyright\'>Copyright @ 2018 Coherix</div>");
document.writeln("    </footer>");