document.writeln("<header id=\'header\'>");
document.writeln("        <div class=\'wrapper headWrap\'>");
document.writeln("            <h1 id=\'logo\'>");
document.writeln("                <img src=\'./img/home/logo.png\'>");
document.writeln("            </h1>");
document.writeln("            <div class=\'navWrap\'>");
document.writeln("                <div class=\'languageWrap\'>");
document.writeln("                    <ul class=\'langList\'>");
document.writeln("                        <li class=\'langItem\'>US</li>");
document.writeln("                        <li class=\'langItem\'>EN</li>");
document.writeln("                        <li class=\'langItem\'>DE</li>");
document.writeln("                        <li class=\'langItem\'>ES</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'navigationWrap\'>");
document.writeln("                    <nav class=\'navigation\'>");
document.writeln("                        <ul class=\'navList\'>");
document.writeln("                            <li class=\'navItem\'><a href=\'#\'>Invest</a></li>");
document.writeln("                            <li class=\'navItem\'><a href=\'#\'>Home</a></li>");
document.writeln("                            <li class=\'navItem xl\'>");
document.writeln("								<a href=\'products.html\'>Products</a>");
document.writeln("								<div class=\'xia\'>");
document.writeln("									<div class=\'xia1\'>");
document.writeln("										<div class=\'xia1_1\'><a href=\'products.html\'>Predator3D</a></div>");
document.writeln("										<div class=\'xia1_1 ac\'>");
document.writeln("											<a href=\'\'>Robust3D <i class=\'iconRit\'></i></a>");
document.writeln("											<div class=\'xia2\'>");
document.writeln("												<div class=\'xia2_1\'>");
document.writeln("													<a href=\'\'>Piston Assembly</a>");
document.writeln("												</div>");
document.writeln("												<div class=\'xia2_1\'>");
document.writeln("													<a href=\'rollingfingerfollowerassembly.html\'>Rolling Finger Follower Assembly</a>");
document.writeln("												</div>");
document.writeln("												<div class=\'xia2_1\'>");
document.writeln("													<a href=\'\'>Valve Assembly</a>");
document.writeln("												</div>");
document.writeln("												<div class=\'xia2_1\'>");
document.writeln("													<a href=\'\'>Volume Measurement</a>");
document.writeln("												</div>");
document.writeln("												<div class=\'xia2_1\'>");
document.writeln("													<a href=\'\'>Flexible End-of-Line Inspection</a>");
document.writeln("												</div>");
document.writeln("											</div>");
document.writeln("										</div>");
document.writeln("										<div class=\'xia1_1\'>Saber3D </div>");
document.writeln("										");
document.writeln("									</div>");
document.writeln("									");
document.writeln("								</div>");
document.writeln("							</li>");
document.writeln("                            <li class=\'navItem\'><a href=\'#\'>Platforms</a></li>");
document.writeln("                            <li class=\'navItem\'><a href=\'#\'>Resources</a></li>");
document.writeln("                            <li class=\'navItem\'><a href=\'#\'>About us</a></li>");
document.writeln("                            <li class=\'navItem\'><a href=\'zaxis.html\'>Z-axis</a></li>");
document.writeln("							<li>");
document.writeln("								<img class=\'img_tab1\' src=\'img/home/search.png\' >");
document.writeln("							</li>");
document.writeln("                        </ul>");
document.writeln("                    </nav>");
document.writeln("                    <span class=\'iSearch\'></span>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </header>");
document.writeln("	<div class=\'ss_box1\'>");
document.writeln("		<div class=\'ss_box2\'>");
document.writeln("			<input type=\'text\' placeholder=\'Search\'>");
document.writeln("			<img class=\'img_tab2\' src=\'img/search/search.png\' >");
document.writeln("		</div>");
document.writeln("		<img class=\'xx\' src=\'img/search/close.png\'>");
document.writeln("	</div>");